# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: The Science Museum Audio Guide
email: your-email@example.com
description: > # this means to ignore newlines until "baseurl:"
  The Science Museum Audio Guide.
baseurl: "/WebAudioPlayer" # the subpath of your site, e.g. /blog
audio_path: "/audio/"
episode_hero_path: "/assets/img/stops/"
url: "https://thesciencemuseum.github.io/" # the base hostname & protocol for your site
logo: #"/assets/img/logo/masthead-sml-logo.png"   #"/assets/img/logo/audio-guide.png"
twitter_username:
github_username:
menu_heading: #"Not Selecting Anything anymore! "
index_page_text: # "Welcome to the Science Museum audio guide"
headphones_icon_color: "/assets/img/icons/headphones-dark.png"
headphones_icon_light: "/assets/img/icons/headphones-light.png"

# Build settings
markdown: kramdown

# Version settings (version number below is used for cache busting CSS and JS)
version_number: 2.0.1.3
